# 코딩 테스트 연습문제 - sql

### 체감 난이도: 2
### JOIN, SUB QUERY, MONTH 활용
### https://school.programmers.co.kr/learn/courses/30/lessons/157341

## JOIN 활용
SELECT DISTINCT(CAR_ID) FROM CAR_RENTAL_COMPANY_CAR CAR
JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY HISTORY
USING(CAR_ID)
WHERE MONTH(HISTORY.START_DATE) = 10 AND CAR.CAR_TYPE = '세단'
ORDER BY CAR_ID DESC

## SUB QUERY 활용
-- SELECT DISTINCT(CAR_ID) FROM CAR_RENTAL_COMPANY_CAR
-- WHERE CAR_TYPE = "세단"
-- AND CAR_ID IN (SELECT CAR_ID
--                 FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
--                 WHERE MONTH(START_DATE) = 10)
-- ORDER BY CAR_ID DESC